services:
    game_server:
        image: lugobots/server:${SERVER_VERSION:-latest}
        platform: linux/amd64
        command: play --dev-mode --listening-duration=${LISTENING_DURATION:-50ms} --grpc-port=${GAME_GRPC_PORT:-5000} --timer-mode=${TIMER_MODE:-wait} --quiet
        ports:
            - '${GAME_GRPC_PORT:-5000}:${GAME_GRPC_PORT:-5000}'
            - '${GAME_FRONTEND_PORT:-8080}:8080'
        healthcheck:
            test: ['CMD', 'grpc-health-probe', '-addr=game_server:${GAME_GRPC_PORT:-5000}']
            interval: 2s
            timeout: 10s
            retries: 3
            start_period: 10s
        environment:
            - HOME_TEAM_NAME=${HOME_TEAM_NAME:-HOME}
            - AWAY_TEAM_NAME=${AWAY_TEAM_NAME:-AWAY}
        volumes:
            - ../../recordings:/recordings
