services:
    game_server:
        image: lugobots/server:${SERVER_VERSION:-latest}
        platform: linux/amd64
        command: play --dev-mode --listening-duration=${LISTENING_DURATION:-50ms} --grpc-port=${GAME_GRPC_PORT:-5000} --timer-mode=${TIMER_MODE:-wait} --quiet --record-path=/recordings/batata
        ports:
            - '${GAME_GRPC_PORT:-5000}:${GAME_GRPC_PORT:-5000}'
            - '${GAME_FRONTEND_PORT:-8080}:8080'
        healthcheck:
            test: ['CMD', 'grpc-health-probe', '-addr=game_server:${GAME_GRPC_PORT:-5000}']
            interval: 2s
            timeout: 10s
            retries: 3
            start_period: 10s
        environment:
            - HOME_TEAM_NAME=${HOME_TEAM_NAME:-HOME}
            - AWAY_TEAM_NAME=${AWAY_TEAM_NAME:-AWAY}
        volumes:
            - ../../recordings:/recordings
    player_home_01:
        image: oven/bun:latest
        working_dir: /app
        volumes:
            - ${PROJECT_PATH:-../../}:/app
        command: bun example/bot/src/main.ts
        depends_on:
            game_server:
                condition: service_healthy
        environment:
            - BOT_NUMBER=1
            - BOT_TEAM=${PLAYER_SIDE:-home}
            - BOT_GRPC_URL=game_server:${GAME_GRPC_PORT:-5000}
            - BOT_LOG_ON=${BOT_LOG_ON:-false}
            - LOG_ON_DISPUTING=${LOG_ON_DISPUTING:-false}
            - LOG_ON_DEFENDING=${LOG_ON_DEFENDING:-false}
            - LOG_ON_HOLDING=${LOG_ON_HOLDING:-false}
            - LOG_ON_SUPPORTING=${LOG_ON_SUPPORTING:-false}
            - LOG_GOALKEEPER=${LOG_GOALKEEPER:-false}
    player_home_02:
        image: oven/bun:latest
        working_dir: /app
        command: bun example/bot/src/main.ts
        depends_on:
            game_server:
                condition: service_healthy
        volumes:
            - ${PROJECT_PATH:-../../}:/app
        environment:
            - BOT_NUMBER=2
            - BOT_TEAM=${PLAYER_SIDE:-home}
            - BOT_GRPC_URL=game_server:${GAME_GRPC_PORT:-5000}
            - BOT_LOG_ON=${BOT_LOG_ON:-false}
            - LOG_ON_DISPUTING=${LOG_ON_DISPUTING:-false}
            - LOG_ON_DEFENDING=${LOG_ON_DEFENDING:-false}
            - LOG_ON_HOLDING=${LOG_ON_HOLDING:-false}
            - LOG_ON_SUPPORTING=${LOG_ON_SUPPORTING:-false}
            - LOG_GOALKEEPER=${LOG_GOALKEEPER:-false}
    player_home_03:
        image: oven/bun:latest
        working_dir: /app
        command: bun example/bot/src/main.ts
        depends_on:
            game_server:
                condition: service_healthy
        volumes:
            - ${PROJECT_PATH:-../../}:/app
        environment:
            - BOT_NUMBER=3
            - BOT_TEAM=${PLAYER_SIDE:-home}
            - BOT_GRPC_URL=game_server:${GAME_GRPC_PORT:-5000}
            - BOT_LOG_ON=${BOT_LOG_ON:-false}
            - LOG_ON_DISPUTING=${LOG_ON_DISPUTING:-false}
            - LOG_ON_DEFENDING=${LOG_ON_DEFENDING:-false}
            - LOG_ON_HOLDING=${LOG_ON_HOLDING:-false}
            - LOG_ON_SUPPORTING=${LOG_ON_SUPPORTING:-false}
            - LOG_GOALKEEPER=${LOG_GOALKEEPER:-false}
    player_home_04:
        image: oven/bun:latest
        working_dir: /app
        command: bun example/bot/src/main.ts
        depends_on:
            game_server:
                condition: service_healthy
        volumes:
            - ${PROJECT_PATH:-../../}:/app
        environment:
            - BOT_NUMBER=4
            - BOT_TEAM=${PLAYER_SIDE:-home}
            - BOT_GRPC_URL=game_server:${GAME_GRPC_PORT:-5000}
            - BOT_LOG_ON=${BOT_LOG_ON:-false}
            - LOG_ON_DISPUTING=${LOG_ON_DISPUTING:-false}
            - LOG_ON_DEFENDING=${LOG_ON_DEFENDING:-false}
            - LOG_ON_HOLDING=${LOG_ON_HOLDING:-false}
            - LOG_ON_SUPPORTING=${LOG_ON_SUPPORTING:-false}
            - LOG_GOALKEEPER=${LOG_GOALKEEPER:-false}
    player_home_05:
        image: oven/bun:latest
        working_dir: /app
        command: bun example/bot/src/main.ts
        depends_on:
            game_server:
                condition: service_healthy
        volumes:
            - ${PROJECT_PATH:-../../}:/app
        environment:
            - BOT_NUMBER=5
            - BOT_TEAM=${PLAYER_SIDE:-home}
            - BOT_GRPC_URL=game_server:${GAME_GRPC_PORT:-5000}
            - BOT_LOG_ON=${BOT_LOG_ON:-false}
            - LOG_ON_DISPUTING=${LOG_ON_DISPUTING:-false}
            - LOG_ON_DEFENDING=${LOG_ON_DEFENDING:-false}
            - LOG_ON_HOLDING=${LOG_ON_HOLDING:-false}
            - LOG_ON_SUPPORTING=${LOG_ON_SUPPORTING:-false}
            - LOG_GOALKEEPER=${LOG_GOALKEEPER:-false}
    player_home_06:
        image: oven/bun:latest
        working_dir: /app
        command: bun example/bot/src/main.ts
        depends_on:
            game_server:
                condition: service_healthy
        volumes:
            - ${PROJECT_PATH:-../../}:/app
        environment:
            - BOT_NUMBER=6
            - BOT_TEAM=${PLAYER_SIDE:-home}
            - BOT_GRPC_URL=game_server:${GAME_GRPC_PORT:-5000}
            - BOT_LOG_ON=${BOT_LOG_ON:-false}
            - LOG_ON_DISPUTING=${LOG_ON_DISPUTING:-false}
            - LOG_ON_DEFENDING=${LOG_ON_DEFENDING:-false}
            - LOG_ON_HOLDING=${LOG_ON_HOLDING:-false}
            - LOG_ON_SUPPORTING=${LOG_ON_SUPPORTING:-false}
            - LOG_GOALKEEPER=${LOG_GOALKEEPER:-false}
    player_home_07:
        image: oven/bun:latest
        working_dir: /app
        command: bun example/bot/src/main.ts
        depends_on:
            game_server:
                condition: service_healthy
        volumes:
            - ${PROJECT_PATH:-../../}:/app
        environment:
            - BOT_NUMBER=7
            - BOT_TEAM=${PLAYER_SIDE:-home}
            - BOT_GRPC_URL=game_server:${GAME_GRPC_PORT:-5000}
            - BOT_LOG_ON=${BOT_LOG_ON:-false}
            - LOG_ON_DISPUTING=${LOG_ON_DISPUTING:-false}
            - LOG_ON_DEFENDING=${LOG_ON_DEFENDING:-false}
            - LOG_ON_HOLDING=${LOG_ON_HOLDING:-false}
            - LOG_ON_SUPPORTING=${LOG_ON_SUPPORTING:-false}
            - LOG_GOALKEEPER=${LOG_GOALKEEPER:-false}
    player_home_08:
        image: oven/bun:latest
        working_dir: /app
        command: bun example/bot/src/main.ts
        depends_on:
            game_server:
                condition: service_healthy
        volumes:
            - ${PROJECT_PATH:-../../}:/app
        environment:
            - BOT_NUMBER=8
            - BOT_TEAM=${PLAYER_SIDE:-home}
            - BOT_GRPC_URL=game_server:${GAME_GRPC_PORT:-5000}
            - BOT_LOG_ON=${BOT_LOG_ON:-false}
            - LOG_ON_DISPUTING=${LOG_ON_DISPUTING:-false}
            - LOG_ON_DEFENDING=${LOG_ON_DEFENDING:-false}
            - LOG_ON_HOLDING=${LOG_ON_HOLDING:-false}
            - LOG_ON_SUPPORTING=${LOG_ON_SUPPORTING:-false}
            - LOG_GOALKEEPER=${LOG_GOALKEEPER:-false}
    player_home_09:
        image: oven/bun:latest
        working_dir: /app
        command: bun example/bot/src/main.ts
        depends_on:
            game_server:
                condition: service_healthy
        volumes:
            - ${PROJECT_PATH:-../../}:/app
        environment:
            - BOT_NUMBER=9
            - BOT_TEAM=${PLAYER_SIDE:-home}
            - BOT_GRPC_URL=game_server:${GAME_GRPC_PORT:-5000}
            - BOT_LOG_ON=${BOT_LOG_ON:-false}
            - LOG_ON_DISPUTING=${LOG_ON_DISPUTING:-false}
            - LOG_ON_DEFENDING=${LOG_ON_DEFENDING:-false}
            - LOG_ON_HOLDING=${LOG_ON_HOLDING:-false}
            - LOG_ON_SUPPORTING=${LOG_ON_SUPPORTING:-false}
            - LOG_GOALKEEPER=${LOG_GOALKEEPER:-false}
    player_home_10:
        image: oven/bun:latest
        working_dir: /app
        command: bun example/bot/src/main.ts
        depends_on:
            game_server:
                condition: service_healthy
        volumes:
            - ${PROJECT_PATH:-../../}:/app
        environment:
            - BOT_NUMBER=10
            - BOT_TEAM=${PLAYER_SIDE:-home}
            - BOT_GRPC_URL=game_server:${GAME_GRPC_PORT:-5000}
            - BOT_LOG_ON=${BOT_LOG_ON:-false}
            - LOG_ON_DISPUTING=${LOG_ON_DISPUTING:-false}
            - LOG_ON_DEFENDING=${LOG_ON_DEFENDING:-false}
            - LOG_ON_HOLDING=${LOG_ON_HOLDING:-false}
            - LOG_ON_SUPPORTING=${LOG_ON_SUPPORTING:-false}
            - LOG_GOALKEEPER=${LOG_GOALKEEPER:-false}
    player_home_11:
        image: oven/bun:latest
        working_dir: /app
        command: bun example/bot/src/main.ts
        depends_on:
            game_server:
                condition: service_healthy
        volumes:
            - ${PROJECT_PATH:-../../}:/app
        environment:
            - BOT_NUMBER=11
            - BOT_TEAM=${PLAYER_SIDE:-home}
            - BOT_GRPC_URL=game_server:${GAME_GRPC_PORT:-5000}
            - BOT_LOG_ON=${BOT_LOG_ON:-false}
            - LOG_ON_DISPUTING=${LOG_ON_DISPUTING:-false}
            - LOG_ON_DEFENDING=${LOG_ON_DEFENDING:-false}
            - LOG_ON_HOLDING=${LOG_ON_HOLDING:-false}
            - LOG_ON_SUPPORTING=${LOG_ON_SUPPORTING:-false}
            - LOG_GOALKEEPER=${LOG_GOALKEEPER:-false}
    player_away_01:
        image: ${AWAY_BOT:-lugobots/level-1:latest}
        platform: linux/amd64
        environment:
            - BOT_NUMBER=1
            - BOT_TEAM=${OPPONENT_SIDE:-away}
            - BOT_GRPC_URL=game_server:${GAME_GRPC_PORT:-5000}
            - MODE=${MODE:-default} # default zombies statues kids defenses
        restart: unless-stopped
        depends_on:
            game_server:
                condition: service_healthy
    player_away_02:
        image: ${AWAY_BOT:-lugobots/level-1:latest}
        platform: linux/amd64
        environment:
            - BOT_NUMBER=2
            - BOT_TEAM=${OPPONENT_SIDE:-away}
            - BOT_GRPC_URL=game_server:${GAME_GRPC_PORT:-5000}
            - MODE=${MODE:-default} # default zombies statues kids defenses
        restart: unless-stopped
        depends_on:
            game_server:
                condition: service_healthy
    player_away_03:
        image: ${AWAY_BOT:-lugobots/level-1:latest}
        platform: linux/amd64
        environment:
            - BOT_NUMBER=3
            - BOT_TEAM=${OPPONENT_SIDE:-away}
            - BOT_GRPC_URL=game_server:${GAME_GRPC_PORT:-5000}
            - MODE=${MODE:-default} # default zombies statues kids defenses
        restart: unless-stopped
        depends_on:
            game_server:
                condition: service_healthy
    player_away_04:
        image: ${AWAY_BOT:-lugobots/level-1:latest}
        platform: linux/amd64
        environment:
            - BOT_NUMBER=4
            - BOT_TEAM=${OPPONENT_SIDE:-away}
            - BOT_GRPC_URL=game_server:${GAME_GRPC_PORT:-5000}
            - MODE=${MODE:-default} # default zombies statues kids defenses
        restart: unless-stopped
        depends_on:
            game_server:
                condition: service_healthy
    player_away_05:
        image: ${AWAY_BOT:-lugobots/level-1:latest}
        platform: linux/amd64
        environment:
            - BOT_NUMBER=5
            - BOT_TEAM=${OPPONENT_SIDE:-away}
            - BOT_GRPC_URL=game_server:${GAME_GRPC_PORT:-5000}
            - MODE=${MODE:-default} # default zombies statues kids defenses
        restart: unless-stopped
        depends_on:
            game_server:
                condition: service_healthy
    player_away_06:
        image: ${AWAY_BOT:-lugobots/level-1:latest}
        platform: linux/amd64
        environment:
            - BOT_NUMBER=6
            - BOT_TEAM=${OPPONENT_SIDE:-away}
            - BOT_GRPC_URL=game_server:${GAME_GRPC_PORT:-5000}
            - MODE=${MODE:-default} # default zombies statues kids defenses
        restart: unless-stopped
        depends_on:
            game_server:
                condition: service_healthy
    player_away_07:
        image: ${AWAY_BOT:-lugobots/level-1:latest}
        platform: linux/amd64
        environment:
            - BOT_NUMBER=7
            - BOT_TEAM=${OPPONENT_SIDE:-away}
            - BOT_GRPC_URL=game_server:${GAME_GRPC_PORT:-5000}
            - MODE=${MODE:-default} # default zombies statues kids defenses
        restart: unless-stopped
        depends_on:
            game_server:
                condition: service_healthy
    player_away_08:
        image: ${AWAY_BOT:-lugobots/level-1:latest}
        platform: linux/amd64
        environment:
            - BOT_NUMBER=8
            - BOT_TEAM=${OPPONENT_SIDE:-away}
            - BOT_GRPC_URL=game_server:${GAME_GRPC_PORT:-5000}
            - MODE=${MODE:-default} # default zombies statues kids defenses
        restart: unless-stopped
        depends_on:
            game_server:
                condition: service_healthy
    player_away_09:
        image: ${AWAY_BOT:-lugobots/level-1:latest}
        platform: linux/amd64
        environment:
            - BOT_NUMBER=9
            - BOT_TEAM=${OPPONENT_SIDE:-away}
            - BOT_GRPC_URL=game_server:${GAME_GRPC_PORT:-5000}
            - MODE=${MODE:-default} # default zombies statues kids defenses
        restart: unless-stopped
        depends_on:
            game_server:
                condition: service_healthy
    player_away_10:
        image: ${AWAY_BOT:-lugobots/level-1:latest}
        platform: linux/amd64
        environment:
            - BOT_NUMBER=10
            - BOT_TEAM=${OPPONENT_SIDE:-away}
            - BOT_GRPC_URL=game_server:${GAME_GRPC_PORT:-5000}
            - MODE=${MODE:-default} # default zombies statues kids defenses
        restart: unless-stopped
        depends_on:
            game_server:
                condition: service_healthy
    player_away_11:
        image: ${AWAY_BOT:-lugobots/level-1:latest}
        platform: linux/amd64
        environment:
            - BOT_NUMBER=11
            - BOT_TEAM=${OPPONENT_SIDE:-away}
            - BOT_GRPC_URL=game_server:${GAME_GRPC_PORT:-5000}
            - MODE=${MODE:-default} # default zombies statues kids defenses
        depends_on:
            game_server:
                condition: service_healthy
